# Generated by Django 4.2.9 on 2024-01-25 19:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('CR', 'Card'), ('AC', 'Account')], default='CR', max_length=2, verbose_name='Тип платежа')),
                ('account_type', models.CharField(max_length=100, verbose_name='Тип карты/счёта')),
                ('owner_surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('owner_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('owner_patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=21, verbose_name='Лимит средств')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=21, verbose_name='Сумма платежа')),
                ('status', models.CharField(choices=[('WT', 'Waiting for payment'), ('PY', 'Payed'), ('DC', 'Cancelled')], default='WT', max_length=2, verbose_name='Статус платежа')),
                ('companydetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='requests_table.companydetails', verbose_name='Реквизиты')),
            ],
        ),
    ]
